services:
  - type: web
    name: job-listing-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
